config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users, only: [:index, :show] do
    get 'confirm', to: 'invitations#confirm'
    resources :invitations, only: [:new, :create]
  end

  resources :cars, only: [:index, :new, :show, :create]

  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  validates :name, presence: true
  
end

app/models/car_file.rb
class CarFile < ApplicationRecord
  
  validates :name, presence: true, uniqueness: true
  validates :pros, presence: true
  validates :cons, presence: true

end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user

  def self.confirmed_record?(id1, id2)
    case1 = !Invitation.where(user_id: id1, friend_id: id2, confirmed: true).empty?
    case2 = !Invitation.where(user_id: id2, friend_id: id1, confirmed: true).empty?
    case1 || case2
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  
  has_one_attached :image
  has_many :cars, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :pending_invitations, -> { where confirmed: false }, class_name: 'Invitation', foreign_key: "friend_id" 
  
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def friends
    sent_confirmations = Invitation.where(user_id: id, confirmed: true).pluck(:friend_id)
    received_confirmations = Invitation.where(friend_id: id, confirmed: true).pluck(:user_id)
    ids = sent_confirmations + received_confirmations
    User.where(id: ids)
  end

  def friend_with?(user)
    Invitation.confirmed_record?(id, user.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :image])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :image])
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @user = current_user
    @friends = current_user.friends
  
    if params[:query].present?
      sql_query = "name ILIKE :query OR specs ILIKE :query"
      @cars = Car.where(sql_query, query: "%#{params[:query]}%")
    else
      @cars = Car.select { |car| car.user_id != current_user.id }
    end
    
  end

  def new
    @car = Car.new
  end

  def show
    @car = Car.find(params[:id])
    @owner = User.find(@car.user_id)
    if CarFile.find_by(name: @car.name)
      file = CarFile.find_by(name: @car.name)
      @pros = file.pros
      @cons = file.cons
    end

    user_friends = current_user.friends
    owner_friends = @owner.friends
    @common_friends = user_friends & owner_friends
    @similar_cars = Car.select{ |car| car.id != @car.id && (car.name == @car.name || car.price == @car.price) }.take(2)
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    @car.save

    redirect_to car_path(@car)
  end

  private

  def car_params
    params.require(:car).permit(:name, :price, :specs, :photo)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def new
    @friend = User.find(params[:user_id])
    @invitation = Invitation.new
  end

  def create
    @invitation = Invitation.new(invitation_params)
    @friend = User.find(params[:user_id])
    @invitation.user = current_user
    @invitation.friend_id = @friend.id
    @invitation.save

    redirect_to user_path(@friend)
  end

  def confirm
    @friend = User.find(params[:user_id])
    @invitation = current_user.pending_invitations.find_by(user_id: @friend.id)
    @invitation.confirmed = true
    @invitation.save
    redirect_to user_path(@friend)
  end

  private

  def invitation_params
    params.require(:invitation).permit(:message)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  
  def home
  end

  def dashboard
    @user = current_user
    @friends = current_user.friends
    @pending_invitations = current_user.pending_invitations
    @cars = current_user.cars
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.select { |user| user.id != current_user.id }
    @current_user = current_user
  end

  def show
    @user = User.find(params[:id])
    @current_user = current_user
    @cars = @user.cars
    check = false
    Invitation.all.each { |invitation| check = true if (invitation.user_id == @user.id || invitation.user_id == current_user.id)  && (invitation.friend_id == @user.id || invitation.friend_id == current_user.id) && invitation.confirmed == false }
    @check = check
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
  <div class="container mt-5 text-center">
    <h4>Find your perfect car</h4>
    <%= form_tag cars_path, method: :get do %>
    <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a car"
  %>
    <%= submit_tag "Search", class: "btn btn-primary mt-3 mb-4" %>
    <% end %>
    <h4>Results</h4>
    <% @cars.each do |car| %>
    <div class="card mt-4">
      <div class="card-body">
        <h5 class="card-title"><%= link_to car.name, car_path(car), :class => "btn-car-link" %></h5>
        <% if car.photo.attached? %>
        <%= image_tag car.photo, :class => "avatar-large" %>
        <% else %>
        <%= image_tag "car-placeholder.png", :class => "avatar-large" %>
        <% end %>

        <% check = @friends & car.user.friends %>
        <% if !check.empty? && !@friends.include?(car.user) %>
        <p>You have a common relationship with the car's owner!</p>
        <p>(<%= @user.first_name %> => <%= check[0].first_name %> => <%= link_to car.user.first_name, user_path(car.user), :class => "link-reset" %>)</p>

        <% elsif @friends.include?(car.user) %>
        <p>You are directly friends with the car's owner. Contact that person now!</p>
        <p>(<%= @user.first_name %> => <%= link_to car.user.first_name, user_path(car.user), :class => "link-reset" %>)</p>

        <% else %>
        <p>You have no common friends with the owner!</p>
        <% end %>

      </div>
    </div>
    <% end %>
    <%= link_to "Refresh List", cars_path, :class => "link-reset" %>
  </div>

app/views/cars/new.html.erb
<div class="container mt-5 mb-3">
  <h4>Add a car</h4>
  <%= simple_form_for(@car) do |f| %>
  <%= f.input :name %>
  <%= f.input :price %>
  <%= f.input :specs %>
  <%= f.label :photo, "You can upload a Picture:" %><br>
  <%= f.file_field :image %><br>
  <hr>
  <%= f.submit %>
  <% end %>
  <p><%= link_to "Back", :back, :class => "link-reset" %></p>
</div>

app/views/cars/show.html.erb
<div class="container mt-5 text-center">
  <h4>Car fact sheet</h4>
  <div class="card mt-4">
    <div class="card-body">
      <h5 class="card-title"><%= @car.name %></h5>
      <% if @car.photo.attached? %>
      <%= image_tag @car.photo, :class => "avatar-large" %>
      <% else %>
      <%= image_tag "car-placeholder.png", :class => "avatar-large" %>
      <% end %>
      <p class="card-text">Price per day: <%= @car.price %></p>
      <p class="card-text">Specs: <%= @car.specs %></p>
      <p class="card-text">Owner: <%= @owner.first_name %></p>
      <% if @owner.image.attached? %>
      <%= image_tag @owner.image, :class => "avatar" %>
      <% end %>
    </div>
    <h4>Pros & Cons:</h4>
    <% if @pros && @cons %>
    <p>Pros: <%= @pros %></p>
    <p>Cons: <%= @cons %></p>
    <% else %>
    <p>Car data unknown</p>
    <% end %>
    <h4>Common friends:</h4>
    <% if @common_friends.length > 0 %>
    <% @common_friends.each do |friend| %>
    <p><%= friend.first_name %></p>
    <% end %>
    <% else %>
    <p>No common friends</p>
    <% end %>
    <h4>Similar cars:</h4>
    <% if @similar_cars.length > 0 %>
    <% @similar_cars.each do |car| %>
    <p><%= link_to car.name, car_path(car), :class => "btn-car-link" %></p>
    <% end %>
    <% else %>
    <p>No similar cars found</p>
    <% end %>
  </div>
  <p><%= link_to "Back", :back, :class => "link-reset" %></p>
</div>

app/views/invitations/new.html.erb
<div class="container mt-5">
  <h4>Friend Request</h4>
  <%= simple_form_for [ @friend, @invitation ] do |f| %>
  <%= f.input :message %>
  <%= f.submit %>
  <% end %>
  <p><%= link_to "Back", :back, :class => "link-reset" %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>CARMarket</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
</head>

<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</body>

</html>

app/views/pages/dashboard.html.erb
  <div class="container mt-5 text-center">
    <h2 class="mb-2">Welcome to your dashboard <%= @user.first_name %>!</h2>
    <h4>My friends</h4>
    <% @friends.each do |friend| %>
    <div class="card mt-4">
      <div class="card-body">
        <h5 class="card-title"><%= link_to friend.first_name, user_path(friend), :class => "btn-member-link" %></h5>
      </div>
    </div>
    <% end %>
    <h4 class="mt-4">My cars</h4>
    <% @cars.each do |car| %>
    <div class="card mt-4">
      <div class="card-body">
        <h5 class="card-title"><%= link_to car.name, car_path(car), :class => "btn-car-link" %></h5>
        <% if car.photo.attached? %>
        <%= image_tag car.photo, :class => "avatar-large" %>
        <% else %>
        <%= image_tag "car-placeholder.png", :class => "avatar-large" %>
        <% end %>
      </div>
    </div>
    <% end %>
    <% if !@pending_invitations.empty? %>
    <h5 class="mt-4">Pending invitations:</h5>
    <% @pending_invitations.each do |invitation| %>
    <% if invitation.user_id != @user.id %>
    <div class="card mt-4">
      <div class="card-body">
        <h5 class="card-title"><%= link_to "Accept request", user_confirm_path(User.find(invitation.user_id)), :class => "btn-member-link"  %></h5>
        <p>from: <%= User.find(invitation.user_id).first_name %></p>
        <p>message: <%= invitation.message %></p>
        <p>sent: <%= invitation.created_at %></p>
      </div>
    </div>
    <% end %>
    <% end %>
    <% else %>
    <h5 class="mt-4 mb-3">You have no pending invitations</h5>
    <% end %>
    <p><%= link_to "Back", :back, :class => "link-reset" %></p>
  </div>

app/views/pages/friends.html.erb
  <div class="container mt-5 mr-2 text-center">
    <% @friends.each do |friend| %>
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        <h5 class="card-title"><%= friend.first_name %></h5>
      </div>
    </div>
    <% end %>
    <h4>Pending requests</h4>
    <p><%= @user.pending_invitations %></p>
  </div>

app/views/pages/home.html.erb
<div class="container">
  <div id="home-page-car">
    <div class="full-screen">
      <div class="slider-content">
        <div class="slider-content-inner">
          <div class="row slider-content-inner-one">
            <div class="col-lg-7">
              <h2>
                <span>Cartopia</span>
                <br>
                <%= image_tag "logo.png", :class => "car-brand" %>
                THE Marketplace for cars
              </h2>
              <p>Connect with cool people and cool cars.</p>
              <div class="row">
                <% if user_signed_in? %>
                <div class="btn bg-car-primary mt-10 p-2 ml-2 mr-4">
                  <%= link_to "/cars", :class => "link-reset" do %>
                  <p class="btn-inner-container mb-0 pl-2 pr-2"> Access cars </p>
                  <% end %>
                </div>
                <% else %>
                <div class="btn bg-car-primary mt-10 p-2 ml-2 mr-4">
                  <%= link_to new_user_registration_path, :class => "link-reset" do %>
                  <p class="btn-inner-container mb-0 pl-2 pr-2"> Sign up </p>
                  <% end %>
                </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <section class="section-padding">
      <div class="row">
        <div class="col-12 text-center">
          <div class="section-title">
            <h6>Why us?</h6>
            <h3>Our Core Features</h3>
            <i class="fas fa-cog home-icon mt-10"></i>
          </div>
        </div>
      </div>
      <div class="custom-container">
        <div class="row our-features">
          <div class="col-md-4 col-sm-12 feature-main text-center">
            <div class="single-feature">
              <h4>Clean design</h4>
              <p>Gain a clear overview of available cars.</p>
            </div>
          </div>
          <div class="col-md-4 col-sm-12 feature-main text-center">
            <div class="single-feature">
              <h4>User-friendly</h4>
              <p>Easily search for contacts and cars.</p>
            </div>
          </div>
          <div class="col-md-4 col-sm-12 feature-main text-center">
            <div class="single-feature">
              <h4>Intuitive</h4>
              <p>Find your dream car and hit the road soon!</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <footer>
      <div id="footerone">
        <div class="row">
          <div class="col-12 text-center">
            <p class="copy-write mb-3">Copyright © 2020 <strong>Cartopia</strong> | All Rights Reserved</p>
          </div>
        </div>
      </div>
    </footer>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
<div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= notice %>
</div>
<% end %>
<% if alert %>
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= alert %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
  <%= image_tag "logo" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "View cars", cars_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Add car", new_car_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Members", "/users", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown ml-4">
        <% if current_user.image.attached? %>
        <%= image_tag current_user.image, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
        <%= image_tag "https://eu.ui-avatars.com/api/?name=#{current_user.first_name}+#{current_user.last_name}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Dashboard", "/dashboard", class: "dropdown-item" %>
          <%= link_to "Account details", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/index.html.erb
<div class="container mt-5 text-center">
  <h4>Members</h4>
  <% @users.each do |user| %>
  <div class="card mt-4">
    <div class="card-body">
      <h5 class="card-title"><%= link_to user.first_name, user_path(user), :class => "btn-member-link" %><small class="ml-2">(<%= user.friends.length %>)</small></h5>
    </div>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container mt-5 text-center">
  <h4>Member profile</h4>
  <div class="card mt-4">
    <div class="card-body">
      <h5 class="card-title">First name: <%= @user.first_name %></h5>
      <p class="card-text">Last name: <%= @user.last_name %></p>
      <% if @user.image.attached? %>
      <%= image_tag @user.image, :class => "avatar" %>
      <% else %>
      <%= image_tag "https://eu.ui-avatars.com/api/?name=#{@user.first_name}+#{@user.last_name}", :class => "avatar" %>
      <% end %>
    </div>
    <% if @current_user.friend_with?(@user) %>
    <p>You are friends</p>
    <% elsif !@current_user.friend_with?(@user) && !@check %>
    <p><%= link_to "Request", new_user_invitation_path(@user), :class => "btn-member-link" %></p>
    <% else %>
    <p>Request pending</p>
    <% end %>
  </div>
  <h4 class="mt-4">Member's cars</h4>
  <% @cars.each do |car| %>
  <div class="card mt-4">
    <div class="card-body">
      <h5 class="card-title"><%= link_to car.name, car_path(car), :class => "btn-car-link" %></h5>
      <% if car.photo.attached? %>
      <%= image_tag car.photo, :class => "avatar-large" %>
      <% else %>
      <%= image_tag "car-placeholder.png", :class => "avatar-large" %>
      <% end %>
    </div>
  </div>
  <% end %>
  <p><%= link_to "Back", :back, :class => "link-reset" %></p>
</div>